// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package ma.projet.sgrh.grpc;

public interface CreateChambreRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CreateChambreRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string type = 1;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>string type = 1;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>double prix = 2;</code>
   * @return The prix.
   */
  double getPrix();

  /**
   * <code>bool disponible = 3;</code>
   * @return The disponible.
   */
  boolean getDisponible();
}
