// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package ma.projet.sgrh.grpc;

public interface ReservationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ReservationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string client_name = 2;</code>
   * @return The clientName.
   */
  java.lang.String getClientName();
  /**
   * <code>string client_name = 2;</code>
   * @return The bytes for clientName.
   */
  com.google.protobuf.ByteString
      getClientNameBytes();

  /**
   * <code>string chambre_number = 3;</code>
   * @return The chambreNumber.
   */
  java.lang.String getChambreNumber();
  /**
   * <code>string chambre_number = 3;</code>
   * @return The bytes for chambreNumber.
   */
  com.google.protobuf.ByteString
      getChambreNumberBytes();

  /**
   * <code>string date_debut = 4;</code>
   * @return The dateDebut.
   */
  java.lang.String getDateDebut();
  /**
   * <code>string date_debut = 4;</code>
   * @return The bytes for dateDebut.
   */
  com.google.protobuf.ByteString
      getDateDebutBytes();

  /**
   * <code>string date_fin = 5;</code>
   * @return The dateFin.
   */
  java.lang.String getDateFin();
  /**
   * <code>string date_fin = 5;</code>
   * @return The bytes for dateFin.
   */
  com.google.protobuf.ByteString
      getDateFinBytes();

  /**
   * <code>string preferences = 6;</code>
   * @return The preferences.
   */
  java.lang.String getPreferences();
  /**
   * <code>string preferences = 6;</code>
   * @return The bytes for preferences.
   */
  com.google.protobuf.ByteString
      getPreferencesBytes();
}
