// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package ma.projet.sgrh.grpc;

public final class Reservation {
  private Reservation() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateReservationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateReservationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateReservationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateReservationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetReservationByIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetReservationByIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteReservationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeleteReservationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReservationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReservationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAllReservationsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAllReservationsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAllReservationsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAllReservationsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteReservationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeleteReservationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateClientRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateClientRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateClientResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateClientResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateChambreRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateChambreRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateChambreResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateChambreResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021reservation.proto\"|\n\030CreateReservation" +
      "Request\022\021\n\tclient_id\030\001 \001(\t\022\022\n\nchambre_id" +
      "\030\002 \001(\t\022\022\n\ndate_debut\030\003 \001(\t\022\020\n\010date_fin\030\004" +
      " \001(\t\022\023\n\013preferences\030\005 \001(\t\"\210\001\n\030UpdateRese" +
      "rvationRequest\022\n\n\002id\030\001 \001(\t\022\021\n\tclient_id\030" +
      "\002 \001(\t\022\022\n\nchambre_id\030\003 \001(\t\022\022\n\ndate_debut\030" +
      "\004 \001(\t\022\020\n\010date_fin\030\005 \001(\t\022\023\n\013preferences\030\006" +
      " \001(\t\"\'\n\031GetReservationByIdRequest\022\n\n\002id\030" +
      "\001 \001(\t\"&\n\030DeleteReservationRequest\022\n\n\002id\030" +
      "\001 \001(\t\"\211\001\n\023ReservationResponse\022\n\n\002id\030\001 \001(" +
      "\t\022\023\n\013client_name\030\002 \001(\t\022\026\n\016chambre_number" +
      "\030\003 \001(\t\022\022\n\ndate_debut\030\004 \001(\t\022\020\n\010date_fin\030\005" +
      " \001(\t\022\023\n\013preferences\030\006 \001(\t\"\033\n\031GetAllReser" +
      "vationsRequest\"H\n\032GetAllReservationsResp" +
      "onse\022*\n\014reservations\030\001 \003(\0132\024.Reservation" +
      "Response\",\n\031DeleteReservationResponse\022\017\n" +
      "\007message\030\001 \001(\t\"T\n\023CreateClientRequest\022\013\n" +
      "\003nom\030\001 \001(\t\022\016\n\006prenom\030\002 \001(\t\022\r\n\005email\030\003 \001(" +
      "\t\022\021\n\ttelephone\030\004 \001(\t\"a\n\024CreateClientResp" +
      "onse\022\n\n\002id\030\001 \001(\t\022\013\n\003nom\030\002 \001(\t\022\016\n\006prenom\030" +
      "\003 \001(\t\022\r\n\005email\030\004 \001(\t\022\021\n\ttelephone\030\005 \001(\t\"" +
      "F\n\024CreateChambreRequest\022\014\n\004type\030\001 \001(\t\022\014\n" +
      "\004prix\030\002 \001(\001\022\022\n\ndisponible\030\003 \001(\010\"S\n\025Creat" +
      "eChambreResponse\022\n\n\002id\030\001 \001(\t\022\014\n\004type\030\002 \001" +
      "(\t\022\014\n\004prix\030\003 \001(\001\022\022\n\ndisponible\030\004 \001(\0102\200\004\n" +
      "\022ReservationService\022D\n\021CreateReservation" +
      "\022\031.CreateReservationRequest\032\024.Reservatio" +
      "nResponse\022D\n\021UpdateReservation\022\031.UpdateR" +
      "eservationRequest\032\024.ReservationResponse\022" +
      "M\n\022GetAllReservations\022\032.GetAllReservatio" +
      "nsRequest\032\033.GetAllReservationsResponse\022F" +
      "\n\022GetReservationById\022\032.GetReservationByI" +
      "dRequest\032\024.ReservationResponse\022J\n\021Delete" +
      "Reservation\022\031.DeleteReservationRequest\032\032" +
      ".DeleteReservationResponse\022;\n\014CreateClie" +
      "nt\022\024.CreateClientRequest\032\025.CreateClientR" +
      "esponse\022>\n\rCreateChambre\022\025.CreateChambre" +
      "Request\032\026.CreateChambreResponseB\030\n\024ma.pr" +
      "ojet.hotel.grpcP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_CreateReservationRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CreateReservationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateReservationRequest_descriptor,
        new java.lang.String[] { "ClientId", "ChambreId", "DateDebut", "DateFin", "Preferences", });
    internal_static_UpdateReservationRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_UpdateReservationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateReservationRequest_descriptor,
        new java.lang.String[] { "Id", "ClientId", "ChambreId", "DateDebut", "DateFin", "Preferences", });
    internal_static_GetReservationByIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_GetReservationByIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetReservationByIdRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_DeleteReservationRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_DeleteReservationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeleteReservationRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_ReservationResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_ReservationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReservationResponse_descriptor,
        new java.lang.String[] { "Id", "ClientName", "ChambreNumber", "DateDebut", "DateFin", "Preferences", });
    internal_static_GetAllReservationsRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_GetAllReservationsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAllReservationsRequest_descriptor,
        new java.lang.String[] { });
    internal_static_GetAllReservationsResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_GetAllReservationsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAllReservationsResponse_descriptor,
        new java.lang.String[] { "Reservations", });
    internal_static_DeleteReservationResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_DeleteReservationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeleteReservationResponse_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_CreateClientRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_CreateClientRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateClientRequest_descriptor,
        new java.lang.String[] { "Nom", "Prenom", "Email", "Telephone", });
    internal_static_CreateClientResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_CreateClientResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateClientResponse_descriptor,
        new java.lang.String[] { "Id", "Nom", "Prenom", "Email", "Telephone", });
    internal_static_CreateChambreRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_CreateChambreRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateChambreRequest_descriptor,
        new java.lang.String[] { "Type", "Prix", "Disponible", });
    internal_static_CreateChambreResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_CreateChambreResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateChambreResponse_descriptor,
        new java.lang.String[] { "Id", "Type", "Prix", "Disponible", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
